#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo "Usage: walk_index [DIR]"
    echo ""
    echo "Walk DIR and run generate_index.py on every README.md found"

    exit 22
elif [ $# -gt 1 ]; then
    echo "Warning: Ignoring extra arguments: ${@:2}"
fi

files=$(find $1 -type f | grep _index.md)

for file in $files; do
    echo "Regenerating $file ..."
    python ./scripts/generate_index.py $file $(dirname $file)
done
